### ISSUE TITLE
[New]: Learning Path for Hugo

### ISSUE THREAD

**Issue by nikiljos** [tinkerhub/TinkerHub-Learning-Paths#111]
### Path Name

Hugo

### Additional info

```markdown
https://gohugo.io/

https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpOnyRlyS-liKL5ReHDcj4G3
```

### Already existing path

- [X] I searched on [https://paths.tinkerhub.org/](https://paths.tinkerhub.org/) and found that the learning path doesnt exist.

**Comment by nikiljos** [comment]
I'm unable to find much resources related to hugo 😥

These are the only ones I found out
 - https://gohugo.io/
 - https://flaviocopes.com/start-blog-with-hugo/
 - https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpOnyRlyS-liKL5ReHDcj4G3

**Comment by LunaticHacker** [comment]
@nikiljos what were you expecting? 
what is there to learn about a template engine? 
are we just stat padding the number of learning paths now?

**Comment by nikiljos** [comment]
> @nikiljos what were you expecting?
> what is there to learn about a template engine?
> are we just stat padding the number of learning paths now?

@LunaticHacker 
I wanted to learn hugo but could not find a lot of resources....
Not sure whether there is much to learn but as a beginner I personally felt I need to learn it to implement it.... 
There is something to learn in it right?

Open for your suggestions... Not sure if such a learning path is necessary...

**Comment by LunaticHacker** [comment]
@nikiljos
> Not sure if such a learning path is necessary...

It is not. Hugo is dead simple all you need to do is to read the documentation, learning paths are not supposed to replace documentations for simple technologies. It should be about guiding the learner to correct resources in the correct chronology to an otherwise messy topic to learn and grasp.(thus the name)

**Comment by nikiljos** [comment]
@gautamkrishnar Maybe we could close this issue if this is an unnecessary learning path... What's your opinion

**Comment by gautamkrishnar** [comment]
@nikiljos there are tons of learning videos on youtube. Yes, we can close this for now.
