### ISSUE TITLE
New Learning Path: Docker

### ISSUE THREAD

**Issue by GopikrishnanSasikumar** [tinkerhub/TinkerHub-Learning-Paths#34]
**Learning Path Name:** 
Docker learning path 
**Learning Path Info:** 
How to get started with docker. Should start with what all stuffs to learn before diving into docker like bash, terminal commands...etc.

**Comment by BMidhun** [comment]
What is Docker?

What are Docker images and containers?

What is Docker CLI and Docker server/daemon?

What is Docker Hub?

How to run the hello-world image from Docker Hub?

Understand 
docker run, 
docker create, 
docker start, 
docker exec, 
docker stop and
docker kill commands with their options.

What constitutes a docker image and a container?

How to create custom docker images?

Understand docker build command with options and the process.

What is the purpose of using a base image in a Dockerfile?

Create simple server using Node or any backend framework of your choice in a docker container. Connect to the server inside the container from your system's browser.

What is Docker Compose and Why it is used?

Learn how to connect multiple containers in docker-compose.

Understand how to write a docker-compose.yaml file.

Understand docker-compose commands.

Understand the restart policies used in docker-compose.

**Comment by nikiljos** [comment]
https://tinkerhub.org/learn/docker
