### ISSUE TITLE
Add page explaining how to add/update learning paths.

### ISSUE THREAD

**Issue by GopikrishnanSasikumar** [tinkerhub/TinkerHub-Learning-Paths#43]
**Is your feature request related to a problem? Please describe.**
Right now on clicking the plus button we are redirecting to GitHub repo. Which doesn't make a lot of people clear about how to update the learning paths. 

**Describe the solution you'd like**

Let's have A UI with step by step instructions on how to use Hugo to add/update learning paths.

Create a video on how to add/update learning paths and embed the video also in the page.

**Comment by LunaticHacker** [comment]
Do we need a new UI? why not just link to the [section](https://github.com/tinkerhub-org/TinkerHub-Learning-Paths#how-to-add-a-new-learning-path) instead, we can embed the video to the readme too.

**Comment by gautamkrishnar** [comment]
@LunaticHacker Looks good to me, @GopikrishnanSasikumar WDYT? do we need a seprate documentation?

**Comment by GopikrishnanSasikumar** [comment]
Ya then let's do that. I will make a video and put the PR.

**Comment by gautamkrishnar** [comment]
Readme would be sufficient for this, closing this one.
