### ISSUE TITLE
tinkerhub.org/learn gives 404

### ISSUE THREAD

**Issue by nikiljos** [tinkerhub/TinkerHub-Learning-Paths#47]
![image](https://user-images.githubusercontent.com/57913645/124252623-c38d2b80-db44-11eb-9628-624260c980b2.png)

https://tinkerhub.org/learn Has this link changed?

**Comment by LunaticHacker** [comment]
Probably related to changing the org name

**Comment by nikiljos** [comment]
Any new link?

**Comment by LunaticHacker** [comment]
github pages deployed to [this](https://tinkerhub.github.io/learn/) link, but all hrefs and resources are failing to load because of hardcorded values, looks like custom domain settings are cleared in that [repo](https://github.com/tinkerhub/learn) we need to update that.

**Comment by nikiljos** [comment]
Was tinkerhub.org CNAME records updated to the new github pages URL? Seems like tinkerhub.org/learn is pointing to https://tinkerhub-org.github.io/learn instead of https://tinkerhub.github.io/learn

**Comment by LunaticHacker** [comment]
@GopikrishnanSasikumar can you take a look at this?

**Comment by nikiljos** [comment]
If we change the resource links in https://github.com/tinkerhub/learn to relative links instead of hard coding links to tinkerhub.org/learn we can view the site perfectly in https://tinkerhub.github.io/learn/ .... See it working fine with relative links in my forked repo https://github.com/nikiljos/learn and preview my fork live in https://tinkerhub-learn.netlify.app/

**Comment by nikiljos** [comment]
Also couldn't we make future github actions production builds use the relative links instead of tinkerhub.org/learn links?

**Comment by nikiljos** [comment]
If this idea works fine, Chek out this PR https://github.com/tinkerhub/learn/pull/1

**Comment by LunaticHacker** [comment]
* No that files shouldn't be edited manually.
* The URL is hardcoded in the [config file](https://github.com/tinkerhub/TinkerHub-Learning-Paths/blob/main/config.toml) .
* Ideally someone with admin access should fix this by fixing custom URL problem.
* The only thing we should do is updating the workflow

**Comment by nikiljos** [comment]
But isn't it better to be having relative URLs instead of hardcoding the domain..... what if we want to change it to learn.tinkerhub.org in future. Also if we change the existing  ones manually to relative URLs and handle the future ones with github actions itself wont the portal work fine

**Comment by LunaticHacker** [comment]
You can just change to baseUrl ="/"  in the config and rebuild instead of manually changing everything,

**Comment by nikiljos** [comment]
That's cool.... I just did it when i saw learning path down for long..... You can close that PR 😀

**Comment by LunaticHacker** [comment]
FYI i dont have access to repos to close or merge PRs you should ping someone with admin access if you want this issue fixed

**Comment by rohittp0** [comment]
All sorted [Learning Paths](https://tinkerhub.github.io/learn/) now working.
I am closing this issue. Please reopen if any further discussion is needed.

**Comment by LunaticHacker** [comment]
[This](https://tinkerhub.org/learn) is still 404

**Comment by rohittp0** [comment]
> [This](https://tinkerhub.org/learn) is still 404

Yeah, it has not yet been linked to tinkerhub.org domain. Currently working on it. It will be done ASAP

**Comment by gautamkrishnar** [comment]
@rohittp0 instead of setting https://tinkerhub.github.io/  you could've set the old domain istelf. I guess the problem here is with the repo name of https://github.com/tinkerhub/tinkerhub-org.github.io. You should rename this repo to https://github.com/tinkerhub/tinkerhub.github.io

**Comment by nikiljos** [comment]
Still what I can't understand is why can't these be relative URLs ? Won't it solve any such problems in the future?

**Comment by gautamkrishnar** [comment]
@rohittp0 its not anything related to code. This is just due to the recent change in our org url. Using absoulute url is entirley ok.

**Comment by gautamkrishnar** [comment]
Inorder to make the urls relative we need to do some code change. I will take a look at it sometime later @nikiljos

**Comment by rohittp0** [comment]
> @rohittp0 instead of setting https://tinkerhub.github.io/ you could've used the old domain istelf.
> 
> I guess the problem here is with the repo name of https://github.com/tinkerhub/tinkerhub-org.github.io. You should rename this repo to https://github.com/tinkerhub/tinkerhub.github.io. Once you are done with this change please try hitting /learn route, it should work fine if we are still using the github pages. If its working please revert the change of domain you had made here [016ac5b](https://github.com/tinkerhub/TinkerHub-Learning-Paths/commit/016ac5b837cb7921ec659b9d3389602e7adfd10e) in the code.

Thanks to @gautamkrishnar  everything is back to working. 

https://tinkerhub.github.io/learn/  This link will no longer be working.
